project:
  type: website
  output-dir: docs

website:
  title: "Hadrien Oliveri"
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Outreach
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: lux
    css: style.css
    toc: true
    page-layout: full
